version: '3'

services:
  ml:
    image: stonent/adapter-ml
    depends_on:
      - rabbitmq
      - postgres
  loader:
    image: stonent/adapter-loader
    depends_on:
      - rabbitmq
      - postgres
      - ml
  rabbitmq:
    image: stonent/adapter-rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  postgres:
      image: stonent/adapter-postgres
      restart: always
  chainlink:
    image: stonent/adapter-chainlink
    command: local node -p /chainlink/.password -a /chainlink/.api
    restart: on-failure
    ports:
      - 6688:6688
    depends_on:
      - postgres
    volumes:
      - chainlink:/chainlink

volumes:
  postgres:
  chainlink:
  rabbitmq:
    driver: local
