version: '3'

services:
  ml:
    image: stonent/adapter-ml
    ports:
      - 80:9090
    depends_on:
      - rabbitmq
  loader:
    image: stonent/adapter-loader
    depends_on:
      - rabbitmq
      - ml
  rabbitmq:
    image: stonent/adapter-rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
    driver: local
