version: '3'

services:
  ml:
#    build: ./services/ml
    image: stonent/adapter-ml
    ports:
      - 80:9090
    depends_on:
      - rabbitmq
  loader:
#    build: ./services/loader
    image: stonent/adapter-loader
    depends_on:
      - rabbitmq
      - ml
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
    driver: local
