version: '3'

services:
  loader:
    image: stonent/adapter-loader
    env_file:
      - ./loader.env
    depends_on:
      - rabbitmq
      - postgres
      - ml
    volumes:
      - ./loader.env:/app/loader.env
  chainlink:
    image: stonent/adapter-chainlink
    command: local node -p /chainlink/.password -a /chainlink/.api
    restart: on-failure
    env_file:
      - ./chainlink.env
    ports:
      - 6688:6688
    depends_on:
      - postgres
    volumes:
      - ./.api:/chainlink/.api
      - ./.password:/chainlink/.password
  ml:
    image: stonent/adapter-ml
    ports:
    - 9191:9191
    depends_on:
      - rabbitmq
      - postgres
  rabbitmq:
    image: stonent/adapter-rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  postgres:
      image: stonent/adapter-postgres
      restart: always

volumes:
  postgres:
  rabbitmq:
